# Generated by Django 4.1.4 on 2022-12-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_blog_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.blogpost')),
            ],
            bases=('Blog.blogpost',),
        ),
    ]
