# Generated by Django 4.1.4 on 2022-12-30 12:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', ckeditor.fields.RichTextField()),
                ('cover_images', models.ImageField(blank=True, null=True, upload_to='draft_images')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date_time'],
            },
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
